Refs #17906: Use 1.15+ boilerplate code
theforeman/smart_proxy_dns_plugin_template pull request #5
Opened 2017-01-17 15:08 UTC by ekohl

https://github.com/theforeman/smart-proxy/pull/492 adds the boilerplate to the smart proxy. This reduces the need for it to be copied into each plugin.

2017-02-07 09:57 UTC, ekohl commented
This can now be merged. I suppose we should create a 1.13-stable branch as well.

2017-02-08 09:07 UTC, domcleal requested changes

2017-02-08 09:07 UTC, domcleal commented on test/dns_plugin_template_record_test.rb
> +  def test_create_ptr_v4
`ptr_v6`

2017-02-08 10:29 UTC, ekohl commented on test/dns_plugin_template_record_test.rb
> +  def test_create_ptr_v4
Fixed

2017-02-08 10:30 UTC, domcleal approved these changes

2017-02-08 10:31 UTC, merged

2017-02-08 10:31 UTC, domcleal commented
Merged, thanks @ekohl.